version: '3.8'

services:
  frontend:
    image: frontend-project
    ports:
      - 5000:5000
  backend:
    image: backend-project
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis:7.2.4
    restart: unless-stopped