version: '3.8'

services:
  frontend:
    image: frontend-project
    ports:
      - 5000:5000
  backend:
    image: backend-project
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
  redis:
    image: redis:7.2.4
    restart: unless-stopped
  postgres:
    image: postgres:16.2
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - ./database:/var/lib/postgresql/data

volumes:
  database:
