version: '3.8'

services:
  frontend:
    container_name: frontend
    image: frontend-project
    environment:
      - REACT_APP_BACKEND_URL=http://localhost
  backend:
    container_name: backend
    image: backend-project
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
  redis:
    container_name: redis
    image: redis:7.2.4
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres:16.2
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf